python:
  # Install our python package before building the docs
  install:
    - requirements: requirements.txt

      
version: 2
 
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
   configuration: docs/source/conf.py
   builder: html
   fail_on_warning: false

formats:
  - pdf
  - epub
