[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "padepy"
authors = [{name = "Rafael", email = "rafael6braga@gmail.com"}]
dynamic = ["version", "description"]
